(let ([a 5])
  (let ([b (+ a 3)])
    (let ([c (if (>= b 8) 
                 (- b 4) 
                 (+ b 2))])
      (let ([d (if (eq? c 4)
                   (if #t
                       (+ c 100)
                       (- c 100))
                   (if (or #t #f)
                       (- c 2)
                       (+ c 2)))])
        d))))
