(let ([x #f])
  (if (not x)
      (let ([y 10])
        (if (< y 20)
            (let ([z (+ y 5)])
              z)
            (let ([z (- y 5)])
              z)))
      (let ([y 20])
        y)))
