(let ([a 3])
  (let ([b (let ([a 5]) (+ a 2))])
    (if (<= b 10)
        (let ([c (if (> a b) a b)])
          (if (eq? c 5)
              (+ c c)
              (- c 1)))
        (let ([d (if (< a b) (- b a) (- a b))])
          d))))
